FAIL
Kernel panic in run: PANIC at ../../threads/synch.c:223 in lock_release(): assertion `lock_held_by_current_thread (lock)' failed.
Call stack: 0x80042131a2 0x8004209d3b 0x80042187e3 0x8004207187
Translation of call stack:
0x00000080042131a2: debug_panic (lib/kernel/debug.c:32)
0x0000008004209d3b: lock_release (threads/synch.c:225)
0x00000080042187e3: acquire_thread_func (tests/threads/priority-donate-lower.c:50)
0x0000008004207187: kernel_thread (threads/thread.c:394)
